### ISSUE TITLE
请问一下现在这个还能用吗？session_token和邮箱密码都报错

### ISSUE THREAD

**Issue by IIRtyj** [liuhuanshuo/ChatGPT_PyBot#2]
<img width="570" alt="截屏2022-12-13 14 05 26" src="https://user-images.githubusercontent.com/77228657/207239564-bfd48692-981d-4a50-abb2-0325ac9ae393.png">
<img width="248" alt="截屏2022-12-13 14 07 14" src="https://user-images.githubusercontent.com/77228657/207239683-3202f745-13f6-44b4-b17b-0f1eeceb7b9b.png">
终端代理已经配置好了，但还是不行
<img width="1173" alt="截屏2022-12-13 14 08 52" src="https://user-images.githubusercontent.com/77228657/207239951-1f869fe9-b26b-4526-b75f-d074977ab0d5.png">
用python出现报错，应该也是登陆那块的问题

**Comment by liuhuanshuo** [comment]
今天， OPENAI 修改了登录验证的方式，新的登录验证方法正在尝试

**Comment by jeffzhengye** [comment]
@liuhuanshuo 认证方式有办法修复吗？

**Comment by Zcb991** [comment]
和上面图片一样也是登录报错

**Comment by yanshiqwq** [comment]
```
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ChatGPT_PyBot import ChatBot
>>> config = {"email":"jusknjinjum@outlook.com","password":"P0VsflC8"}
>>> chatbot = ChatBot(config, conversation_id=None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\yanshiqwq\AppData\Local\Programs\Python\Python38\lib\site-packages\ChatGPT_PyBot\chatgpt.py", line 36, in __init__
    self.refresh_session()
  File "C:\Users\yanshiqwq\AppData\Local\Programs\Python\Python38\lib\site-packages\ChatGPT_PyBot\chatgpt.py", line 241, in refresh_session
    raise exc
  File "C:\Users\yanshiqwq\AppData\Local\Programs\Python\Python38\lib\site-packages\ChatGPT_PyBot\chatgpt.py", line 238, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "C:\Users\yanshiqwq\AppData\Local\Programs\Python\Python38\lib\site-packages\ChatGPT_PyBot\chatgpt.py", line 256, in login
    auth = OpenAIAuth(email, password, use_proxy, proxy, debug=self.debug)
TypeError: __init__() got multiple values for argument 'debug'
```
